ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: "dev srv"
    init: "npm install"
    command: "npm start"
    
vscode:
  extensions:
    - "gulajavaministudio.mayukaithemevsc"
    - "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/scrimba/vsextensions/vsimba/3.1.6/vspackage"
